### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by redchair123** [jawb/JSVM#1]
you should rename gpl.txt to something more standard like COPYING

**Comment by jawb** [comment]
Done, I thought that's obvious :)

**Comment by redchair123** [comment]
@jawb from https://www.gnu.org/licenses/gpl-howto.html (emphasis mine)

> You should also include a copy of the license itself somewhere in the distribution of your program. All programs, whether they are released under the GPL or LGPL, should include the text version of the GPL. **In GNU programs the license is usually in a file called COPYING.**

(not quite sure why they do that)
