### ISSUE TITLE
Make use of gh-pages

### ISSUE THREAD

**Issue by jpillora** [jawb/JSVM#2]
1. branch `master` to `gh-pages` and push
2. go into the repo settings set default branch to `gh-pages`
3. delete `master` (use `gh-pages` as master)
4. `index.html` will now be served at http://jawb.github.io/JSVM

**Comment by jawb** [comment]
Done .. I never used github pages before, thanks for the quick tutorial

**Comment by jpillora** [comment]
:+1:
